// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvewfbkftvkcdcnlqpjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2ZXdmYmtmdHZrY2RjbmxxcGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDYzNTUsImV4cCI6MjA3MjY4MjM1NX0.RiY8p_uh1UcbXMni-hcMEwQ3qWOMdEOGBZxvdGquUtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});